version: "3"

services:
  app:
    image: qtcreator:latest
    build:
      context: .
      dockerfile: qtcreator.Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/LoAT
    network_mode: host
