runs:
  using: "composite"
  steps:

    - uses: actions/download-artifact@v4
      with:
        name: loat-static-${{ github.sha }}
        path: /usr/local/bin/

    - run: |
        mv /usr/local/bin/loat-static /usr/local/bin/solver
        chmod +x /usr/local/bin/solver
        VERSION=$(solver --version | head -1 | rev | cut -d\  -f 1 | rev)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash

