runs:
  using: "composite"
  steps:

    - uses: dawidd6/action-download-artifact@v3
      with:
        name: loat-static-${{ github.ref_name }}
        path: /usr/local/bin/

    - run: |
        mv /usr/local/bin/loat-static /usr/local/bin/solver
        chmod +x /usr/local/bin/solver
        VERSION=$(solver --version)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
      shell: bash

