name: 'CHC 22 LIA Lin'
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
      repository: chc-comp/chc-comp22-benchmarks
      sparse-checkout: LIA-Lin

    - run: |
        gunzip LIA-Lin/*.gz
        mkdir benchmarks
        mv LIA-Lin/*.smt2 benchmarks

