name: Build LoAT Base Image

on:
  # Automatically run this action on every push to `master` but only
  # if there are changes in the image directory. The image does not 
  # depend on any LoAT sources, so re-build is only necessary when 
  # the configuration of the image itself changes.
  push:
    branches: 
      - master
    paths:
      - 'docker/loat-base-image/**'

  # Also allow this action to be triggered manually via a button in 
  # the GitHub UI.
  workflow_dispatch:

# Config mainly copied from here: 
# https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      # not sure what this step is good for but is was part of the
      # example config:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          # Push resulting image to Docker Hub so it can be used on any machine or other
          # or other pipelines:
          push: true
          # Directory where Dockerfile is located.
          # See: https://github.com/marketplace/actions/build-and-push-docker-images#git-context
          context: "{{defaultContext}}:docker/loat-base-image"
          # Overwrite the `latest` tag which is used to build the LoAT binaries:
          # but also create tag the image with the current commit sha so old 
          # images can still be accessed later:
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/loat-base:latest            
            ${{ secrets.DOCKERHUB_USERNAME }}/loat-base:${{ github.sha }}
