name: Build LoAT

on:
  push:
    branches:
      - master
    paths:
      - 'docker/loat-base-image/**'
      - 'src/**'
      - 'CMakeLists.txt'

  # Also allow this action to be triggered manually via a button in
  # the GitHub UI.
  workflow_dispatch:

jobs:
  build-loat-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LoAT Repository
        uses: actions/checkout@v4
          with:
            lfs: true

      - name: Build LoAT Binary
        uses: addnab/docker-run-action@v3
        with:
          # Build LoAT binary inside the latest pushed base image:
          image: ${{ vars.DOCKERHUB_USERNAME }}/loat-base:latest
          options: -v ${{ github.workspace }}:/LoAT
          shell: bash
          run: |
            mkdir -p /LoAT/build/release
            cd /LoAT/build/release
            cmake -DCMAKE_BUILD_TYPE=Release ../../
            make -j4

      - name: Export LoAT Binary
        uses: actions/upload-artifact@master
        with:
          name: loat-static
          path: build/release/loat-static
